language: java
dist: trusty

before_install:
  - cp travis_settings.xml $HOME/.m2

script:
- mvn clean install

deploy:
  provider: script
  script: "mvn -DskipTests deploy"
  on:
    branch: master

before_cache:
  - "rm -f $HOME/.m2/repository/org/examples"
cache:
  directories:
    - "$HOME/.m2/repository"
